#!/bin/bash

process=$(ps -a | grep projet | cut -d" " -f2)
serial=/dev/serial0

if [ -e testResult ]
then
        sudo touch testResult
else
        sudo rm -f testResult
        sudo touch testResult
        sudo chmod a+w testResult
fi


#TestCase 1
gpio -g mode 20 out
gpio -g write 20 0 #Mouvement detecte
sleep 10
gpio -g write 20 1 #Mouvement termine
gpio -g mode 20 in

sleep 2

echo S >> $serial #Son detecte
sleep 10
echo T >> $serial #Son termine

sleep 3


#TestCase 2
echo S >> $serial #Son detecte
sleep 5
gpio -g mode 20 out
gpio -g write 20 0 #Mouvement detecte
sleep 5
echo T >> $serial #Son termine
sleep 3
gpio -g write 20 1 #Mouvement termine
gpio -g mode 20 in

sleep 3

sudo kill -int $process
